const integrantes = [
    {
        apellido: 'DE ROSA',
        nombre: 'ERNESTO',
        descripcion: 'Jefe de Logistica ',
        equipo: 'Depto. Logística',
        sector: null,
    },
    {
        apellido: 'BASANTA',
        nombre: 'SUSANA',
        descripcion: 'Telefonista',
        equipo: 'Depto. Logística',
        sector: 'Atención al público',
    },
    {
        apellido: 'AGUILAR',
        nombre: 'RAFAEL',
        descripcion: 'Atención al pùblico',
        equipo: 'Depto. Logística',
        sector: 'Atención al público',
    },
    {
        apellido: 'RAVELO',
        nombre: 'ROSALíA',
        descripcion: 'Asistente de Logística',
        equipo: 'Depto. Logística',
        sector: 'Administración / Auditoria',
    },
    {
        apellido: 'RODRIGUEZ',
        nombre: 'MAXIMILIANO',
        descripcion: 'Administración Logística',
        equipo: 'Depto. Logística',
        sector: 'Administración / Auditoria',
    },
    {
        apellido: 'MEDINA',
        nombre: 'SANTIAGO',
        descripcion: 'Asistente Operativo ',
        equipo: 'Depto. Logística',
        sector: 'Administración / Auditoria',
    },
    {
        apellido: 'CARNALES',
        nombre: 'RUBEN',
        descripcion: 'Responsable de Recepciòn y Almacenaje',
        equipo: 'Depto. Logística',
        sector: 'Depósito',
    },
    {
        apellido: 'TRAVIESO',
        nombre: 'RUBEN',
        descripcion: 'Responsable de Expedición',
        equipo: 'Depto. Logística',
        sector: 'Depósito',
    },
    {
        apellido: 'NAVIA',
        nombre: 'MARCELO',
        descripcion: 'Responsable de Picking',
        equipo: 'Depto. Logística',
        sector: 'Depósito',
    },
    {
        apellido: 'PERELLI',
        nombre: 'FABRIZIO',
        descripcion: 'Equipo de Tráfico',
        equipo: 'Depto. Logística',
        sector: 'Depósito',
    },
    {
        apellido: 'MATTOS',
        nombre: 'ALEXANDER',
        descripcion: 'Equipo de Tráfico',
        equipo: 'Depto. Logística',
        sector: 'Depósito',
    },
    {
        apellido: 'De MELLO',
        nombre: 'LEONARDO',
        descripcion: 'Equipo de Tráfico',
        equipo: 'Depto. Logística',
        sector: 'Depósito',
    },
    {
        apellido: 'TRUCELLI',
        nombre: 'LUIS',
        descripcion: 'Equipo de Logìstica',
        equipo: 'Depto. Logística',
        sector: 'Depósito',
    },
    {
        apellido: 'LORENZO',
        nombre: 'RODRIGO',
        descripcion: 'Equipo de Logìstica',
        equipo: 'Depto. Logística',
        sector: 'Depósito',
    },
    {
        apellido: 'MILLACET',
        nombre: 'MATHIAS',
        descripcion: 'Equipo de Logìstica',
        equipo: 'Depto. Logística',
        sector: 'Depósito',
    },
    {
        apellido: 'PORCIÚNCULA',
        nombre: 'MICHAEL',
        descripcion: 'Equipo de Logìstica',
        equipo: 'Depto. Logística',
        sector: 'Depósito',
    },
    {
        apellido: 'PUENTE',
        nombre: 'MARCEL',
        descripcion: 'Equipo de Tráfico',
        equipo: 'Depto. Logística',
        sector: 'Depósito',
    },
    {
        apellido: 'PARADO',
        nombre: 'FERNANDO',
        descripcion: 'Equipo de Logìstica',
        equipo: 'Depto. Logística',
        sector: 'Depósito',
    },
    {
        apellido: 'FERNANDEZ',
        nombre: 'JONATHAN',
        descripcion: 'Equipo de Logìstica',
        equipo: 'Depto. Logística',
        sector: 'Depósito',
    },
    {
        apellido: 'BAIS',
        nombre: 'FERNANDO',
        descripcion: 'Equipo de Tráfico',
        equipo: 'Depto. Logística',
        sector: 'Depósito',
    },
    {
        apellido: 'CAMARGO',
        nombre: 'MARIA',
        descripcion: 'Equipo de Logìstica',
        equipo: 'Depto. Logística',
        sector: 'Depósito',
    },
    {
        apellido: 'QUIROZ',
        nombre: 'JULIAN',
        descripcion: 'Equipo de Logìstica',
        equipo: 'Depto. Logística',
        sector: 'Depósito',
    },
    {
        apellido: 'DOLGAY',
        nombre: 'MARCOS',
        descripcion: 'Equipo de Logìstica',
        equipo: 'Depto. Logística',
        sector: 'Depósito',
    },
    {
        apellido: 'LAUNAS',
        nombre: 'FEDERICO',
        descripcion: 'Equipo de Tráfico',
        equipo: 'Depto. Logística',
        sector: 'Depósito',
    },
    {
        apellido: 'PICARDO',
        nombre: 'JUAN',
        descripcion: 'Equipo de Logìstica',
        equipo: 'Depto. Logística',
        sector: 'Depósito',
    },
    {
        apellido: 'RIVERO',
        nombre: 'FABIO',
        descripcion: 'Equipo de Logìstica',
        equipo: 'Depto. Logística',
        sector: 'Depósito',
    },
    {
        apellido: 'MAYER',
        nombre: 'FLORENCIA',
        descripcion: 'Gerente de Administraciòn y Finanzas',
        equipo: 'Administración',
        sector: null,
    },
    {
        apellido: 'BANCHERO',
        nombre: 'RODY',
        descripcion: 'Encargado de Administracion ',
        equipo: 'Administración',
        sector: null,
    },
    {
        apellido: 'LANERI',
        nombre: 'DANIELA',
        descripcion: 'Auxiliar Administrativo ',
        equipo: 'Administración',
        sector: null,
    },
    {
        apellido: 'LOPEZ DE HARO',
        nombre: 'DANIEL',
        descripcion: 'Auxiliar Administrativo ',
        equipo: 'Administración',
        sector: null,
    },
    {
        apellido: 'PEÑA',
        nombre: 'CARINA',
        descripcion: 'Auxiliar Administrativo ',
        equipo: 'Administración',
        sector: null,
    },
    {
        apellido: 'STABLE',
        nombre: 'PABLO',
        descripcion: 'Auxiliar Administrativo ',
        equipo: 'Administración',
        sector: null,
    },
    {
        apellido: 'TRIPODI',
        nombre: 'PABLO',
        descripcion: 'Auxiliar Administrativo ',
        equipo: 'Administración',
        sector: null,
    },
    {
        apellido: 'AVILA',
        nombre: 'CLAUDIA',
        descripcion: 'Auxiliar de Importaciones',
        equipo: 'Administración',
        sector: 'Importaciones',
    },
    {
        apellido: 'ROMERO',
        nombre: 'LETICIA',
        descripcion: 'Demand Planner ',
        equipo: 'Administración',
        sector: 'Importaciones',
    },
    {
        apellido: 'OSORIO',
        nombre: 'JOSEFINA',
        descripcion: 'Auxiliar de Importaciones ',
        equipo: 'Administración',
        sector: 'Importaciones',
    },
    {
        apellido: 'GRZABEL',
        nombre: 'ALEX',
        descripcion: 'Jefe Gestión y Desarrollo Humano ',
        equipo: 'Gestión Humana',
        sector: null,
    },
    {
        apellido: 'ROSA',
        nombre: 'JUAN',
        descripcion: 'Responsable de Service ',
        equipo: 'Post-Venta',
        sector: null,
    },
    {
        apellido: 'DI PAOLA',
        nombre: 'ANDRES',
        descripcion: 'Responsable de Service',
        equipo: 'Post-Venta',
        sector: null,
    },
    {
        apellido: 'DALTO',
        nombre: 'ESTEBAN',
        descripcion: 'Auxiliar de Service',
        equipo: 'Post-Venta',
        sector: null,
    },
    {
        apellido: 'BERGARA',
        nombre: 'NICOLAS',
        descripcion: 'Auxiliar de Service',
        equipo: 'Post-Venta',
        sector: null,
    },
    {
        apellido: 'REBUFFO',
        nombre: 'PABLO',
        descripcion: 'Gerente Comercial ',
        equipo: 'Depto Comercial',
        sector: null,
    },
    {
        apellido: 'MACHADO',
        nombre: 'CAROLAINE',
        descripcion: 'Merchandiser',
        equipo: 'Depto Comercial',
        sector: null,
    },
    {
        apellido: 'CASTRO',
        nombre: 'KOKE',
        descripcion: 'Responsable de Linea Pinturas',
        equipo: 'Depto Comercial',
        sector: 'Jefe de Línea',
    },
    {
        apellido: 'RAJCHMAN',
        nombre: 'CLAUDIA',
        descripcion: 'Responsable de Línea Ferretería y Ventas Telefónicas',
        equipo: 'Depto Comercial',
        sector: 'Jefe de Línea',
    },
    {
        apellido: 'VARELA',
        nombre: 'MARCOS',
        descripcion: 'Responsable de Línea Goldex y Herramientas Profesionales',
        equipo: 'Depto Comercial',
        sector: 'Jefe de Línea',
    },
    {
        apellido: 'PIGNATTA',
        nombre: 'VALERIA',
        descripcion: 'Responsable de Línea Bazar ',
        equipo: 'Depto Comercial',
        sector: 'Jefe de Línea',
    },
    {
        apellido: 'GONZALEZ',
        nombre: 'JAVIER',
        descripcion: 'Responsable de Línea Electrodomésticos y Marketing',
        equipo: 'Depto Comercial',
        sector: 'Jefe de Línea',
    },
    {
        apellido: 'OLIVERA',
        nombre: 'SANTIAGO',
        descripcion: 'Responsable de Línea  Echo-Shindaiwa',
        equipo: 'Depto Comercial',
        sector: 'Jefe de Línea',
    },
    {
        apellido: 'ESCOTO',
        nombre: 'ENRIQUE',
        descripcion: 'Promotor de Pinturas',
        equipo: 'Depto Comercial',
        sector: 'Asistentes Técnicos',
    },
    {
        apellido: 'GONZALEZ',
        nombre: 'EDUARDO',
        descripcion: 'Asistente Técnico ',
        equipo: 'Depto Comercial',
        sector: 'Asistentes Técnicos',
    },
    {
        apellido: 'SOCA',
        nombre: 'ANDRES',
        descripcion: 'Asistente Técnico ',
        equipo: 'Depto Comercial',
        sector: 'Asistentes Técnicos',
    },
    {
        apellido: 'PERCIANTE',
        nombre: 'BRUNO',
        descripcion: 'Asistente Técnico ',
        equipo: 'Depto Comercial',
        sector: 'Asistentes Técnicos',
    },
    {
        apellido: 'AÑON ',
        nombre: 'OSVALDO',
        descripcion: 'Vend. Viajante ',
        equipo: 'Depto Comercial',
        sector: 'Vendedores',
    },
    {
        apellido: 'MIGLIERINA',
        nombre: 'RAFAEL',
        descripcion: 'Vendedor de Plaza ',
        equipo: 'Depto Comercial',
        sector: 'Vendedores',
    },
    {
        apellido: 'BERMUDEZ ',
        nombre: 'MARCELO',
        descripcion: 'Vend. Viajante ',
        equipo: 'Depto Comercial',
        sector: 'Vendedores',
    },
    {
        apellido: 'GAUDIOSO ',
        nombre: 'VICENTE',
        descripcion: 'Vend. Viajante ',
        equipo: 'Depto Comercial',
        sector: 'Vendedores',
    },
    {
        apellido: 'MATTOS',
        nombre: 'PABLO',
        descripcion: 'Vend. Viajante ',
        equipo: 'Depto Comercial',
        sector: 'Vendedores',
    },
    {
        apellido: 'VANOLI ',
        nombre: 'ALEJANDRO',
        descripcion: 'Vend. Viajante ',
        equipo: 'Depto Comercial',
        sector: 'Vendedores',
    },
    {
        apellido: 'ETCHEBARNE',
        nombre: 'FERNANDO',
        descripcion: 'Vend. Viajante ',
        equipo: 'Depto Comercial',
        sector: 'Vendedores',
    },
    {
        apellido: 'BALSA ',
        nombre: 'JORGE',
        descripcion: 'Vend. Viajante ',
        equipo: 'Depto Comercial',
        sector: 'Vendedores',
    },
    {
        apellido: 'ROLANDO ',
        nombre: 'MAXIMILIANO',
        descripcion: 'Vend. Viajante ',
        equipo: 'Depto Comercial',
        sector: 'Vendedores',
    },
    {
        apellido: 'DEVINCENZI ',
        nombre: 'ALEJANDRO',
        descripcion: 'Vend. Viajante ',
        equipo: 'Depto Comercial',
        sector: 'Vendedores',
    },
    {
        apellido: 'GARCIA',
        nombre: 'CLAUDIA',
        descripcion: 'Vendedor de Plaza ',
        equipo: 'Depto Comercial',
        sector: 'Vendedores',
    },
    {
        apellido: 'FERNANDEZ',
        nombre: 'GABRIEL',
        descripcion: 'Vend. Viajante ',
        equipo: 'Depto Comercial',
        sector: 'Vendedores',
    },
    {
        apellido: 'MAZZUCO',
        nombre: 'ADRIAN',
        descripcion: 'Vendedor de Plaza ',
        equipo: 'Depto Comercial',
        sector: 'Vendedores',
    },
    {
        apellido: 'CARRIZO',
        nombre: 'ALVARO',
        descripcion: 'Vendedor ',
        equipo: 'Depto Comercial',
        sector: 'Vendedor Telefónico',
    },
    {
        apellido: 'TRIBEL',
        nombre: 'ALEJANDRO',
        descripcion: 'Vendedor ',
        equipo: 'Depto Comercial',
        sector: 'Vendedor Telefónico',
    },
    {
        apellido: 'MISA',
        nombre: 'GONZALO',
        descripcion: 'Vendedor ',
        equipo: 'Depto Comercial',
        sector: 'Vendedor Telefónico',
    },
    {
        apellido: 'BLUTH',
        nombre: 'SYLVINA',
        descripcion: 'Gerente General ',
        equipo: 'Gerencia Gral.',
        sector: null,
    },
    {
        apellido: 'RODRIGUEZ',
        nombre: 'OBDULIO',
        descripcion: 'Auxiliar de Informática ',
        equipo: 'Informática / Diseño',
        sector: null,
    },
    {
        apellido: 'MARTINEZ',
        nombre: 'REYNALDO',
        descripcion: 'Infraestructura y Diseño ',
        equipo: 'Informática / Diseño',
        sector: null,
    },
    {
        apellido: 'SILVEIRA',
        nombre: 'DIEGO',
        descripcion: 'Auxiliar Administrativo ',
        equipo: 'Informática / Diseño',
        sector: null,
    },
    {
        apellido: 'GONZALEZ',
        nombre: 'ANDREA',
        descripcion: 'Asistente de Diseño',
        equipo: 'Informática / Diseño',
        sector: null,
    },
];

const equipos = [...new Set(integrantes.map((i) => i.equipo))];

console.log({ equipos });

const result = equipos.map((e) => ({
    name: e,
    members: integrantes
        .filter((i) => i.equipo === e)
        .map((i) => ({
            firstName: i.nombre,
            lastName: i.apellido,
            role: i.descripcion,
            team: i.equipo,
        })),
}));

console.log({ result: JSON.stringify(result) });
