const integrantes = [
    {
        apellido: 'REBUFFO',
        nombre: 'PABLO',
        descripcion: 'Gerente Comercial ',
        equipo: 'Equipo Comercial',
    },
    {
        apellido: 'NUÑEZ',
        nombre: 'GASTÓN',
        descripcion: 'Asistente Comercial ',
        equipo: 'Equipo Comercial',
    },
    {
        apellido: 'OLIVERA',
        nombre: 'SANTIAGO',
        descripcion: 'Encargado de Negocio ',
        equipo: 'Equipo Comercial',
    },
    {
        apellido: 'PIGNATTA',
        nombre: 'VALERIA',
        descripcion: 'Encargado de Negocio ',
        equipo: 'Equipo Comercial',
    },
    {
        apellido: 'VARELA',
        nombre: 'MARCOS',
        descripcion: 'Encargado de Negocio ',
        equipo: 'Equipo Comercial',
    },
    {
        apellido: 'GONZALEZ',
        nombre: 'JAVIER',
        descripcion: 'Encargado de Negocio / Marketing ',
        equipo: 'Equipo Comercial',
    },
    {
        apellido: 'RAJCHMAN',
        nombre: 'CLAUDIA',
        descripcion: 'Encargado de Negocio ',
        equipo: 'Equipo Comercial',
    },
    {
        apellido: 'CARRIZO',
        nombre: 'ALVARO',
        descripcion: 'Vendedor telefónico',
        equipo: 'Ventas Telefónicas',
    },
    {
        apellido: 'MISA',
        nombre: 'GONZALO',
        descripcion: 'Vendedor telefónico',
        equipo: 'Ventas Telefónicas',
    },
    {
        apellido: 'TRIBEL',
        nombre: 'ALEJANDRO',
        descripcion: 'Vendedor telefónico',
        equipo: 'Ventas Telefónicas',
    },
    {
        apellido: 'PERCIANTE',
        nombre: 'BRUNO',
        descripcion: 'Asistente Técnico ',
        equipo: 'Asistencia Técnica',
    },
    {
        apellido: 'GONZALEZ',
        nombre: 'EDUARDO',
        descripcion: 'Asistente Técnico ',
        equipo: 'Asistencia Técnica',
    },
    {
        apellido: 'SOCA',
        nombre: 'ANDRES',
        descripcion: 'Asistente Técnico ',
        equipo: 'Asistencia Técnica',
    },
    {
        apellido: 'MACHADO',
        nombre: 'CAROLAINE',
        descripcion: 'Merchandiser',
        equipo: 'Merchandiser',
    },
    {
        apellido: 'CASTRO',
        nombre: 'JORGE',
        descripcion: 'Responsable de Negocio',
        equipo: 'Departamento de Pinturas',
    },
    {
        apellido: 'ESCOTO',
        nombre: 'ENRIQUE',
        descripcion: 'Promotor de Pinturas',
        equipo: 'Departamento de Pinturas',
    },
    {
        apellido: 'MAZZUCO',
        nombre: 'ADRIAN',
        descripcion: 'Vendedor externo',
        equipo: 'Ventas Externas',
    },
    {
        apellido: 'AÑON',
        nombre: 'OSVALDO',
        descripcion: 'Vendedor externo',
        equipo: 'Ventas Externas',
    },
    {
        apellido: 'ROLANDO',
        nombre: 'MAXIMILIANO',
        descripcion: 'Vendedor externo',
        equipo: 'Ventas Externas',
    },
    {
        apellido: 'VANOLI',
        nombre: 'ALEJANDRO',
        descripcion: 'Vendedor externo',
        equipo: 'Ventas Externas',
    },
    {
        apellido: 'ETCHEBARNE',
        nombre: 'FERNANDO',
        descripcion: 'Vendedor externo',
        equipo: 'Ventas Externas',
    },
    {
        apellido: 'MIGLIERINA',
        nombre: 'RAFAEL',
        descripcion: 'Vendedor externo',
        equipo: 'Ventas Externas',
    },
    {
        apellido: 'GAUDIOSO',
        nombre: 'VICENTE',
        descripcion: 'Vendedor externo',
        equipo: 'Ventas Externas',
    },
    {
        apellido: 'MATTOS',
        nombre: 'PABLO',
        descripcion: 'Vendedor externo',
        equipo: 'Ventas Externas',
    },
    {
        apellido: 'BALSA',
        nombre: 'JORGE',
        descripcion: 'Vendedor externo',
        equipo: 'Ventas Externas',
    },
    {
        apellido: 'FERNANDEZ',
        nombre: 'GABRIEL',
        descripcion: 'Vendedor externo',
        equipo: 'Ventas Externas',
    },
    {
        apellido: 'DEVINCENZI',
        nombre: 'ALEJANDRO',
        descripcion: 'Vendedor externo',
        equipo: 'Ventas Externas',
    },
    {
        apellido: 'GARCIA',
        nombre: 'CLAUDIA',
        descripcion: 'Vendedor externo',
        equipo: 'Ventas Externas',
    },
    {
        apellido: 'BERMUDEZ',
        nombre: 'MARCELO',
        descripcion: 'Vendedor externo',
        equipo: 'Ventas Externas',
    },
    {
        apellido: 'MAYER',
        nombre: 'FLORENCIA',
        descripcion: 'Gerente de Administración y Finanzas',
        equipo: 'Administración',
    },
    {
        apellido: 'BANCHERO',
        nombre: 'RODY',
        descripcion: 'Encargado de Administración ',
        equipo: 'Administración',
    },
    {
        apellido: 'ROMERO',
        nombre: 'LETICIA',
        descripcion: 'Demand Planner ',
        equipo: 'Administración',
    },
    {
        apellido: 'STABLE',
        nombre: 'PABLO',
        descripcion: 'Auxiliar Administrativo',
        equipo: 'Administración',
    },
    {
        apellido: 'LOPEZ DE HARO',
        nombre: 'DANIEL',
        descripcion: 'Auxiliar Administrativo',
        equipo: 'Administración',
    },
    {
        apellido: 'TRIPODI',
        nombre: 'PABLO',
        descripcion: 'Auxiliar Administrativo',
        equipo: 'Administración',
    },
    {
        apellido: 'PEÑA',
        nombre: 'ADRIANA',
        descripcion: 'Auxiliar Administrativo',
        equipo: 'Administración',
    },
    {
        apellido: 'LANERI',
        nombre: 'DANIELA',
        descripcion: 'Auxiliar Administrativo',
        equipo: 'Administración',
    },
    {
        apellido: 'AVILA',
        nombre: 'CLAUDIA',
        descripcion: 'Auxiliar Administrativo',
        equipo: 'Importaciones',
    },
    {
        apellido: 'OSORIO',
        nombre: 'JOSEFINA',
        descripcion: 'Auxiliar Administrativo',
        equipo: 'Importaciones',
    },
    {
        apellido: 'GRZABEL',
        nombre: 'ALEX',
        descripcion: 'Jefe de Gestión y Desarrollo Humano',
        equipo: 'Gestión Humana',
    },
    {
        apellido: 'MARTINEZ',
        nombre: 'REYNALDO',
        descripcion: 'Responsable de Infraestructura y diseño',
        equipo: 'Informática y diseño',
    },
    {
        apellido: 'GONZALEZ',
        nombre: 'ANDREA',
        descripcion: 'Auxiliar de Informática',
        equipo: 'Informática y diseño',
    },
    {
        apellido: 'RODRIGUEZ',
        nombre: 'OBDULIO',
        descripcion: 'Auxiliar de Informática',
        equipo: 'Informática y diseño',
    },
    {
        apellido: 'SILVEIRA',
        nombre: 'DIEGO',
        descripcion: 'Auxiliar de Informática',
        equipo: 'Informática y diseño',
    },
    {
        apellido: 'BERGARA',
        nombre: 'NICOLAS',
        descripcion: 'Auxiliar de Service',
        equipo: 'Posventa',
    },
    {
        apellido: 'DALTO',
        nombre: 'ESTEBAN',
        descripcion: 'Medio Oficial ',
        equipo: 'Posventa',
    },
    {
        apellido: 'DI PAOLA',
        nombre: 'ANDRES',
        descripcion: 'Responsable de Posventa',
        equipo: 'Posventa',
    },
    {
        apellido: 'ROSA',
        nombre: 'JUAN',
        descripcion: 'Responsable de Posventa',
        equipo: 'Posventa',
    },
    {
        apellido: 'BLUTH',
        nombre: 'SYLVINA',
        descripcion: 'Director',
        equipo: 'Dirección / Gerencia General',
    },
    {
        apellido: 'DE ROSA',
        nombre: 'ERNESTO',
        descripcion: 'Jefe de Logistica ',
        equipo: 'Logística',
    },
    {
        apellido: 'RAVELO',
        nombre: 'ROSALIA',
        descripcion: 'Asistente de Logística',
        equipo: 'Logística',
    },
    {
        apellido: 'RODRIGUEZ',
        nombre: 'MAXIMILIANO',
        descripcion: 'Auxiliar Administrativo',
        equipo: 'Logística',
    },
    {
        apellido: 'BASANTA',
        nombre: 'SUSANA',
        descripcion: 'Telefonista',
        equipo: 'Logística',
    },
    {
        apellido: 'TRAVIESO',
        nombre: 'RUBEN',
        descripcion: 'Encargado de Expedición y Picking',
        equipo: 'Logística',
    },
    {
        apellido: 'CARNALES',
        nombre: 'RUBEN',
        descripcion: 'Encargado de Recepción y Almacenaje',
        equipo: 'Logística',
    },
    {
        apellido: 'NAVIA',
        nombre: 'MARCELO',
        descripcion: 'Responsable de picking',
        equipo: 'Logística',
    },
    {
        apellido: 'DOLGAY',
        nombre: 'MARCOS',
        descripcion: 'Equipo de Logística',
        equipo: 'Logística',
    },
    {
        apellido: 'GONZÁLEZ',
        nombre: 'MARTIN',
        descripcion: 'Equipo de Logística',
        equipo: 'Logística',
    },
    {
        apellido: 'MOLINA',
        nombre: 'WALTER',
        descripcion: 'Equipo de Logística',
        equipo: 'Logística',
    },
    {
        apellido: 'GOUX',
        nombre: 'LUCAS',
        descripcion: 'Equipo de Logística',
        equipo: 'Logística',
    },
    {
        apellido: 'CAMARGO',
        nombre: 'MARIA',
        descripcion: 'Equipo de Logística',
        equipo: 'Logística',
    },
    {
        apellido: 'PICARDO',
        nombre: 'JUAN',
        descripcion: 'Equipo de Logística',
        equipo: 'Logística',
    },
    {
        apellido: 'RIVERO',
        nombre: 'FABIO',
        descripcion: 'Equipo de Logística',
        equipo: 'Logística',
    },
    {
        apellido: 'GARCIA',
        nombre: 'MAXIMILIANO',
        descripcion: 'Chofer ',
        equipo: 'Logística',
    },
    {
        apellido: 'LAUNAS',
        nombre: 'FEDERICO',
        descripcion: 'Tráfico',
        equipo: 'Logística',
    },
    {
        apellido: 'TRUCELLI',
        nombre: 'LUIS',
        descripcion: 'Equipo de Logística',
        equipo: 'Logística',
    },
    {
        apellido: 'AGUILAR',
        nombre: 'RAFAEL',
        descripcion: 'Equipo de Logística',
        equipo: 'Logística',
    },
    {
        apellido: 'MILLACET',
        nombre: 'MATHIAS',
        descripcion: 'Equipo de Logística',
        equipo: 'Logística',
    },
    {
        apellido: 'QUIROZ',
        nombre: 'JULIAN',
        descripcion: 'Equipo de Logística',
        equipo: 'Logística',
    },
    {
        apellido: 'MATTOS',
        nombre: 'ALEXANDER',
        descripcion: 'Chofer',
        equipo: 'Logística',
    },
    {
        apellido: 'PUENTE',
        nombre: 'MARCEL',
        descripcion: 'Tráfico',
        equipo: 'Logística',
    },
    {
        apellido: 'PERELLI',
        nombre: 'FABRIZIO',
        descripcion: 'Chofer ',
        equipo: 'Logística',
    },
    {
        apellido: 'MEDINA',
        nombre: 'SANTIAGO',
        descripcion: 'Equipo de Logística',
        equipo: 'Logística',
    },
];

const equipos = [...new Set(integrantes.map((i) => i.equipo))];

console.log({ equipos });

const result = equipos.map((e) => ({
    name: e,
    integrantes: integrantes.filter((i) => i.equipo === e),
}));

console.log({ result: JSON.stringify(result) });
